[dosbox]
machine = cga

[autoexec]
# This section runs on startup

MOUNT -u a

# Mount the downloaded file (now at /home/dosbox/paktool.ima) as drive A
imgmount a /home/dosbox/paktool.ima -t floppy

# Change to drive A
a:

# Execute your command
pakview.exe cat.pak